### ISSUE TITLE
The Twitter blog says Twemoji would be compliant with Unicode 7.0. But apparently it's not - "slightly smiling face" seems to be missing for example.

### ISSUE THREAD

**Issue by wp9015362** [twitter/twemoji#65] opened 2015-04-08 15:49 UTC
Hello,

the Twitter blog says:

> https://blog.twitter.com/2014/open-sourcing-twitter-emoji-for-everyone says:
> 
> Twemoji is compliant with the latest 7.0 Unicode version

But apparently it's not.

There seem to be some new Emojis in Unicode 7.0, see:

http://emojipedia.org/new-emoji/

Just to name one example, there is the "slightly smiling face" among them for example:

http://emojipedia.org/slightly-smiling-face/

And it's missing from Twemoji.

Again, that's just one example.

Could you please add the missing Emojis to the Twitter "Twemoj" Emoji set?

It would be much appreciated.

Regards

**Comment by iseulde** [comment] 2015-04-08 15:53
Duplicate of #59.

**Comment by WebReflection** [comment] 2015-04-08 15:58
> Coming soon as part of the Unicode 7.0 update.

maybe when the post was written it wasn't in already? Not sure I understand this complain ... in any case, feel free to PR a list of emoji that are not present in twemoji.

**Comment by wp9015362** [comment] 2015-04-08 16:45
> @WebReflection wrote:
> 
> Not sure I understand this complain ... 

So you do not understand this complaint, but you understand those two complaints:

https://github.com/twitter/twemoji/issues/44
https://github.com/twitter/twemoji/issues/48

?

:wink:

**Comment by wp9015362** [comment] 2015-04-08 17:22
PS:

> @WebReflection wrote:
> 
> in any case, feel free to PR a list of emoji that are not present in twemoji.

I am currently not a designer, but:

On the WordPress issue tracker which @pento mentioned in [the other issue](https://github.com/twitter/twemoji/issues/60):

https://core.trac.wordpress.org/ticket/31709

and on the blog from @iseulde :

http://iseulde.com/2014/03/19/secret-new-wordpress-smileys/

I noticed that @jasmussen ("Joen"), seems to be good at it.

So, @jasmussen :

Any chance you could possibly do this?

Your Smileys/Emojis (the attached SVGs [over there](https://core.trac.wordpress.org/ticket/31709) and the other smileys [over there](http://iseulde.com/2014/03/19/secret-new-wordpress-smileys/)) look great.

Regards

**Comment by jasmussen** [comment] 2015-04-08 17:49
> I noticed that @jasmussen ("Joen"), seems to be good at it.

Well I appreciate the vote of confidence. I've done some smileys, and I know how to help edit existing emoji already created. 

But keeping up to date with the unicode emoji standard is a vast undertaking which I can't undertake myself with a day job. Our best hope — including for the quality of the resulting new emoji to be drawn — is probably to hope for Twitter to push out updates once in a while.

Which reminds me: how amazing is it that Twitter have had 800+ emoji created and are giving them away for free? Still blows my mind.

**Comment by wp9015362** [comment] 2015-04-08 18:03
> @jasmussen wrote:
> 
> Which reminds me: how amazing is it that Twitter have had 800+ emoji
> created and are giving them away for free? Still blows my mind.

Well, to be fair, Twitter does not seem to be the only ones who did that. They apparently weren't even the first to do so.

Seems like Emoji One had already done it prior:

http://emojione.com/
https://github.com/Ranks/emojione

:wink:

Besides:

> @jasmussen wrote:
> 
> Our best hope — including for the quality of the resulting new emoji to be drawn —
> is probably to hope for Twitter to push out updates once in a while.

reading through the [Twitter blog post](https://blog.twitter.com/2014/open-sourcing-twitter-emoji-for-everyone), it seems like Twitter might not even have created Twemoji in-house, but rather have ["The Iconfactory"](http://iconfactory.com/) do it for them?

Some more "evidence":

https://twitter.com/Iconfactory/status/530503070548238337

?

:wink:

Well, let's see what @caniszczyk will come up with, as [he said he will investigate internally](https://github.com/twitter/twemoji/issues/60#issuecomment-90937658).

Regards

**Comment by rodrigopolo** [comment] 2015-05-28 00:55
I have created a library which depends on SVGs from this library and I have upgraded the library to support the latest unicode emojis that are already available on iOS8.3 but I can't find many new emojis on this library.

Here is the project:
https://github.com/rodrigopolo/minEmoji

I'm currently using all PNGs I found on the Apple font in this versions:
http://rodrigopolo.github.io/minEmoji/jMinEmoji2/demo.html
http://rodrigopolo.github.io/minEmoji/minEmoji_iOS8/demo.html

So, anyone know when new pictures will be available?

Thanks!

**Comment by WebReflection** [comment] 2015-05-28 09:48
3 identical posts ... @rodrigopolo please do not use opened bugs to promote your library. I am going to remove all of your 3 posts. Eventually feel free to ask a question in one place, or open a new bug. Thank you

**Comment by rodrigopolo** [comment] 2015-05-28 13:22
@WebReflection I'm not promoting anything, I just increasing the probabilities of getting an answer, I was about to open a request (bug) asking for this new emojis but then I found there were 3 bug reports that essentially ask for the same thing (I'll consider merging them if you ask me), so, I'm not earning money nor "internet points", I'm not trolling or doing something bad to some one, just looking for some SVGs to do what exactly people need. I'll share the URL again NOT to promote but to get anyone interested into seeing that it is a real working library:
https://github.com/rodrigopolo/minEmoji

**Comment by WebReflection** [comment] 2016-03-02 21:56
[V2 has landed](https://github.com/twitter/twemoji#unicode-80-and-diversity) with 1661 covered emoji VS just 874 in previous version.

Easy way to update?
prefix `/twemoji.min.js` from MaxCDN via `2/twemoji.min.js` and you're good to go.

**Closed by WebReflection** 2016-03-02 21:56 UTC
