### ISSUE TITLE
SVG sprite

### ISSUE THREAD

**Issue by steelbrain** [twitter/twemoji#90] opened 2015-07-26 22:39 UTC
I have read the previous discussions where you guys discouraged SVG sprites because of the maintainability, but I have another method in mind. Would you like to review a PR which adds a script that you can run to create svg of all the emojis?

**Comment by rodrigopolo** [comment] 2015-07-26 22:48
ImageMagick can convert any SVG into a PNG, I do this to generate a PNG sprite:
```
convert -background none sprite.svg -scale 100x5460 -depth 8 ios8sprite.png
```
[source](https://github.com/rodrigopolo/minEmoji/tree/master/sprite_gen2)

**Comment by steelbrain** [comment] 2015-07-26 22:51
Which means that if we generate an svg sprite, we will automatically have a png sprite, Great :clap:

**Comment by WebReflection** [comment] 2015-07-26 23:52
a sprite is a very bad way to move forward in my opinion because emoji will only grow in number and SVGs are heavy. Nobody wants to download 1MB of emoji sprite to send maybe just a smile,  the CDN  here works pretty well for the current emoji purpose.

All I am saying is that if you manage to generate a sprite that has a reasonable size, "why not",  we could add that too, but having a huge SVG with 700 sub-SVGs is not probably a good idea and maybe you should not waste your time.

Or better: what is the issue you are trying to solve with an SVG sprite? Do you know that SVGs are very heavy to rendered and that rendering them  inside a sprite might even block/freeze some device?

And all other related discussed problems.

**Comment by steelbrain** [comment] 2015-07-26 23:55
I actually already have that script that makes the sprites, so wasting my time is not a thing. Also I was just looking at http://codepen.io/adrianosmond/pen/LCogn about the svg vs png performance.
The problem I was trying to solve with it is the number of all those HTTP requests, I was thinking of creating a single svg and/or png and store that in app cache so it won't be requested ever again (unless it's updated of course).
At the moment, I can create svg sprites and now I am working on a way to convert them to png along with the css and I am sure it won't take much time at all for me.

**Comment by rodrigopolo** [comment] 2015-07-27 04:37
All depends on the scenario…

SVGs are heavier to render than PNGs, fact. So displaying many SVGs will be something bad for the browser, but displaying 140 emojis (thinking of Twitter) doesn´t hurt the browser.

In the other hand we have PNGs, browsers doesn´t have problem displaying a lot of them.

In this two scenarios loading each emoji from a different file (png/svg) isn´t an issue if it is something like a tweet.

The other scenario is loading a lot of tweets with many emojis, loading each PNG file for each emoji could hurt the experience if you want to keep a low http request rate, so here a sprite is handy BUT it will be a huge file, and it could get bigger if it is a SVG sprite, also, having a 2X PNG sprite for HiDPI (Retina) devices is crazy, the file would be huge and it will consume a lot of bandwidth.

The only wat this scenario could be feasible is if you are making an HTML app that has a local storage and it doesn´t load anything from the internet more than the content (a JSON API).

A SVG sprite is bad idea, in any scenario.

Keeping SVG files in order to have an editable emoji is a great idea, loading a few in the browser is not a bad idea and it will look awesome in the browser even if it is a HiDPI device.

So at the end of the day you have to decide which approach is better for your user, your bandwidth and your server.

**Comment by WebReflection** [comment] 2015-07-27 05:31
@rodrigopolo if you think about twitter you don't think about 140 chars, you think  about an infinite stream  of tweets, multiplied 140.

Same as if you think HiDPi, you don't think  maximum  retina 2X, that is 2007,  today it's hard to find devices and laptops or tablets with a device pixel ratio equal to 1 but specially on mobile, higher than 2X is becoming de-facto standard.

Moreover,  HiDPis is not just about 2X, is about having the ability to zoom in with your fingers or browser and still see a sharp representation of the emoji if you use SVG.

As summary, there is a reason SVG is much heavier to render, and there is a reason MaxCDN helped a lot here: you don't download all emojis every time, you just download them  on demand through a well known/resolved CDN domain  that forces the browser to use local cache whenever is possible (most of the time)

On top of that, if I just update one single emoji,  users don't have to download again  the whole big sprites.

Please bear in mind we are stuck at about 700 emoji here, but we are also behind the Unicode schedule which is close, if not over,  a 1000.

Thank you both for your understanding, if you don't mind closing this as non-issue, I'd be happy :)

**Comment by steelbrain** [comment] 2015-07-27 05:33
Makes sense. Thanks for the explaination.

**Closed** 2015-07-27 05:33 UTC
Labels: question

**Comment by rodrigopolo** [comment] 2015-07-27 06:08
@WebReflection You are right, if some app shows a Twitter timeline it could show a lot of tweets, but talking about real world scenarios, talking about the real world, nobody is showing a timeline with thousands of emojis, you can check the real(time) emoji usage here: http://www.emojitracker.com

Also, a mobile app will display only a fraction of the timeline (scroll), anything that doesn't appear in the screen is not being rendered, is in memory and/or in the DOM but not rendered, you can try using the native Twitter app on any mobile phone to check that fact and you will see that there is also no zoom option at all, if it is a web app for desktop usage it really doesn't matter. I know that HiDPI is not about 2X but you can check what bigger brands are doing (Apple, Microsoft, Google) when they work with images on HiDPI displays, most of them have the 2X solution because it works great, knowing that a perfect 20/20 vision looking into a 300DPI/PPI+ display can't distinguish one pixel from the other (I made some tests with the LG G3) it will not look very sharp but it will look good enough.

So again, it depends on the scenario, remember that this library can work for web apps that load content from local or remote web sources. So there are some things to consider before choosing the best solution, like bandwidth + requests (if it applies), client resolution, the client CPU/GPU and memory limits, etc. That will give you an idea on the best solution.

**Comment by WebReflection** [comment] 2015-07-27 06:50
> nobody is showing a timeline with thousands of emojis

twitter, twitter mobile, tweetdeck do ... for instance, and there are posts online including conversations  and  many tweets at once ;-)

emojitracker is a very good tool that shows you nobody would need a sprite since most common used/needed emoji are just a few

I like the fact you are explaining to me, the maintainer of this repo, how emoji  works :D

I just would like to remind you me, and others, have already done these tests on Desktop and Mobile and the usage of many files VS sprite was also discussed and agreed with MaxCDN

No zoom option  is also something I don't understand, this repository is used by million sites, the fact an app doesn't zoom is not the real world, this repository is target agnostic.

But yes, it depends, maybe, I simply think SVG sprite with hundreds emoji  is not as functional and useful as few icons used as sprite ( a more common technique )

Best Rgegards

**Comment by rodrigopolo** [comment] 2015-07-27 07:42
@WebReflection I'm not explaining nor trying to teach you, that would be preaching to the choir, relax, I'm replying to your comments to @steelbrain giving another perspective, I also have a library (that some people use) that does something similar in different ways and [the JavaScript behind it](https://github.com/rodrigopolo/minEmoji/blob/master/jMinEmoji2/js/jMinEmoji2.js) reflects the way I think, like a pragmatic developer, not messing with all the Unicode ranges or anything but with the actual emojis in a regular expression, maybe is not the best approach but it works great.

Twitter, Twitter Mobile, Tweetdeck, etc. are not actually showing thousands of emojis, take a look at the great paper published by Peter-Paul Koch: http://www.quirksmode.org/mobile/viewports.html

I agree about not using a huge SVG sprite.

>A SVG sprite is bad idea, in any scenario.

But enough said about the matter, I only hope that Twitter start creating the missing new emojis, nice to talk to you both.

**Comment by WebReflection** [comment] 2015-07-27 08:09
> not messing with all the Unicode ranges or anything

who is messing with all the Unicode ranges, if I might ask?

**Comment by rodrigopolo** [comment] 2015-07-27 09:10
Ok! XD

**Comment by tresdin** [comment] 2016-10-13 08:59
The sprite is very useful in the case of offline web applications. Those applications are designed to be able to work without network connectivities. That means developers need to prefetch all the emojis at the very first load. And sending thousands of requests at once is generally a bad idea. Also, I think a sprite with few MBs in size is not big. It just has a similar size with a 4MP JPEG image. You know, users often upload hundreds or thousands of those images.

Not having a sprite is the primary reason that forces me to recommend my users not to use twemoji as the default emoji set. It's simply because it's not available when they're offline.

**Comment by WebReflection** [comment] 2016-10-13 09:25
quoting myself:

> Do you know that SVGs are very heavy to render and that rendering them inside a very big sprite might even block/freeze some device?

also quoting myself:

> if you manage to generate a sprite that has a reasonable size, "why not"

Moreover, I don't buy the offline case. If you have Service Workers in place and you cache emoji you'll have your svgs for all the text you've cached and previously downloaded so that what you've seen while connected, is what you'll see seeing while offline (since you cannot download new content).

If the issue is writing down new text and emoji, the phone will provide native emoji so you can do that and the person that will receive such message will be able to read such text while connected.

All I am saying is that (I promise I'll stop quoting myself now)

> a sprite is a very bad way to move forward in my opinion because emoji will only grow in number and SVGs are heavy.

Best Regards

**Comment by tresdin** [comment] 2016-10-13 10:13
@WebReflection 
> Moreover, I don't buy the offline case. If you have Service Workers in place and you cache emoji you'll have your svgs for all the text you've cached and previously downloaded so that what you've seen while connected, is what you'll see seeing while offline (since you cannot download new content).

What about the emojis that have never been used before? They will absolutely not be available while offline.

I actually mean that there should be a better way to prefetch the entire twemoji set, especially when sprites are not going to be implemented. So what will be your recommendations for the issue?

**Comment by WebReflection** [comment] 2016-10-13 10:34
> What about the emojis that have never been used before? They will absolutely not be available while offline.

I've covered that. Either you have a panel with all emoji already fetched, or you are on a phone and it provides native emoji so you see those and you can save them so you'll see your emoji.

How else would you add emoji never used before? Can you give me a practical example?

Anyway, having a sprite might be a solution for some. If you'll PR a bash script capable of generating automatically such sprite we can use it when we publish new versions of the library (or new emoji are added) and keep it in MaxCDN.

**Comment by tresdin** [comment] 2016-10-13 11:49
@WebReflection 
> I've covered that. Either you have a panel with all emoji already fetched, or you are on a phone and it provides native emoji so you see those and you can save them so you'll see your emoji.

Those solutions might work, but they're not guaranteed. Some users will use the apps on PC. And they often type the ASCII characters or the alternative `shortname` like `:D`, `:grin:`. They don't really care about the emoji list. There is no way to make sure that they'll open the list for prefetching the emojis.

> How else would you add emoji never used before? Can you give me a practical example?

As I said, twemoji should support prefetching the entire set, may be via sprites or HTTP2 requests. Let's take an example with HTTP2. The entire set can be served with a single HTTP2 request like this:
```
// The below requests should be served with all files
// in this folder (https://github.com/twitter/twemoji/tree/gh-pages/36x36)
https://twemoji.maxcdn.com/get?version=1&type=png&size=36

// and this folder (https://github.com/twitter/twemoji/tree/gh-pages/2/svg)
https://twemoji.maxcdn.com/get?version=2&type=svg
```
Those urls can be easily parsed on server side for retrieving the expected emoji folder. Then each file in that folder can be pushed via HTTP2 with its respective URL.

I don't think it's a good idea for twemoji to write its own scripts for generating sprites. There are already tools for this task.

**Comment by WebReflection** [comment] 2016-10-13 14:41
> And they often type the ASCII characters or the alternative shortname like :D, :grin:. 

right ... I keep thinking everyone here just writes emoji and uses the js lib but that's not always the case. Thanks for the reminder.

> Those urls can be easily parsed on server side

Not at all, if you understand how a CDN work: it's dumb.
We have zero server side control, we can only purge content, nothing else.

> I don't think it's a good idea for twemoji to write its own scripts for generating sprites. There are already tools for this task.

It wasn't the plan indeed. Whatever works automatically can be used to generate such sprite. Yet nobody pushed a PR capable of doing so, so I think it's rather complicated ... or is it?

We use ai to svgs converter already for assets, maybe there is a way in Inkscape to create proper sprites. If anyone knows how, please share.

**Comment by tresdin** [comment] 2016-10-13 18:37
@WebReflection 

I think it will not be too complicated with a tool. I've tried to generate a twemoji v2 svg sprite using the `svg-sprite` module on `Node.js` and here is the result.
**Files**
[twemoji-svg-sprite.zip](https://github.com/twitter/twemoji/files/527799/twemoji-svg-sprite.zip)
**Fiddle**
https://jsfiddle.net/tresdin/9wfswgws/

Here is the code that I used for generating it.
```
let SVGSpriter = require('svg-sprite');
let fs = require('fs');
let readdir = dir => new Promise((resolve, reject) => {
	fs.readdir(dir, (er, files) => {
		if(er){
			return reject(er);
		}
		resolve(files);
	});
});
let readFile = path => new Promise((resolve, reject) => {
	fs.readFile(path, (er, content) => {
		if(er){
			return reject(er);
		}
		resolve(content);
	})
});
let writeFile = (file, content, options) => new Promise((resolve,reject) => {
	fs.writeFile(file, content, options, er => {
		if(er){
			return reject(er);
		}
		resolve();
	});
});


const EMOJI_DIR = '/home/twemoji/svg';
const EMOJI_DEST = '/home/twemoji';

let spriter = new SVGSpriter({
	mode: {
		css: {
			render: {
				css: true
			}
		}
	}
});

readdir(EMOJI_DIR)
.then(files => Promise.all(files.map(file => {
	let path = EMOJI_DIR + '/' + file;
	return readFile(path).then(content => spriter.add(path, null, content));
})))
.then(() => new Promise((resolve, reject) => {
	spriter.compile((er, result) => {
		if(er){
			return reject(er);
		}
		resolve(result);
	})
}))
.then(result => Promise.all([
	writeFile(EMOJI_DEST + '/sprite.svg', result.css.sprite.contents),
	writeFile(EMOJI_DEST + '/sprite.css', result.css.css.contents)
]));
```

**Comment by WebReflection** [comment] 2016-10-13 18:53
there's no guarantee for the order, right? that `Promise.all` looks good for perf but it's not ideal for CSS mapped sprites ... what if we host simply a list of all assets? would that makes things any better?

It'd be surely easier to implement.

**Comment by WebReflection** [comment] 2016-10-13 19:00
P.S. the right folder for assets is `twemoji/2/svg/` and not the old `twemoji/svg/` one ... there are over 1000 emoji now within assets.

**Comment by tresdin** [comment] 2016-10-13 20:10
@WebReflection 
It won't be a problem if twemoji provides the exact order of all files in JSON format. It's not hard to sort those files in a particular order.

> what if we host simply a list of all assets? would that makes things any better?

I would say no. Developers are already able to get all the assests. It just requires a little more work.

The sprite was actually complied from the files in `twemoji/2/svg/` folder. You can check the sprite to confirm this.
