### ISSUE TITLE
No assets in distributed package after version 12.0.3

### ISSUE THREAD

**Issue by mucsi96** [twitter/twemoji#359] opened 2019-06-06 04:32 UTC
Thank for creating this awesome package! Love it. I discovered a major regression in release `12.0.3`. Not sure if that's expected, but now there is no assets in distributed NPM package. Previously all svgs were in folder `2`. Now I see only JavaScript files.

Version 12.0.3
![image](https://user-images.githubusercontent.com/3163392/59006782-02e0d500-8824-11e9-8be1-0ba993281ff7.png)

Version 12.0.2
![image](https://user-images.githubusercontent.com/3163392/59006939-b053e880-8824-11e9-8cff-ce66c29a9091.png)

**Comment by Crissov** [comment] 2019-06-06 16:28
This is another duplicate of #356.

**Comment by n8downs** [comment] 2019-06-06 22:01
Yep, definitely a +1 for publishing the assets separately

**Closed by n8downs** 2019-06-06 22:01 UTC
