### ISSUE TITLE
Add new Unicode emoji added in Unicode 8.0.0

### ISSUE THREAD

**Issue by KamranMackey** [twitter/twemoji#86] opened 2015-06-26 03:10 UTC
I would love it if you guys could add the new emoji added in Unicode 8.0.0 to the Twemoji library, as Unicode 8.0.0 adds tons of new emoji. :smiley:

**Comment by rodrigopolo** [comment] 2015-06-26 07:24
I also want this to be a reality, sadly, as @WebReflection have told us, the SVGs and AIs files are made by Twitter, this repository deals with the JavaScipt and other libraries to handle that unicode strings into emojis.

I have already asked for new SVGs:
https://github.com/twitter/twemoji/issues/81

I have added some of the new diversity SVGs by changing colors to the files, you can see the complete list here:
http://rodrigopolo.com/files/emojilist/

I also have made a library to deal with new emojis, I'm posting this NOT to promote my library but to show that there is good will to have a full unicode 8 library and that it is something that can be done if there is the intention to do so:
http://rodrigopolo.github.io/minEmoji/jMinEmoji2/demo.html

**Comment by wp9015362** [comment] 2015-09-11 17:35
Duplicate of:

https://github.com/twitter/twemoji/issues/48

**Comment by WebReflection** [comment] 2016-03-02 21:54
[V2 has landed](https://github.com/twitter/twemoji#unicode-80-and-diversity) with 1661 covered emoji VS just 874 in previous version.

Easy way to update?
prefix `/twemoji.min.js` from MaxCDN via `2/twemoji.min.js` and you're good to go.

**Closed by WebReflection** 2016-03-02 21:54 UTC
