### ISSUE TITLE
Pistol emoji wrong in 2.6

### ISSUE THREAD

**Issue by Crissov** [twitter/twemoji#284] opened 2018-04-11 21:46 UTC
[![U+1F52B PISTOL](https://rawgit.com/twitter/twemoji/gh-pages/2/72x72/1f52b.png)](https://github.com/twitter/twemoji/blob/gh-pages/2/72x72/1f52b.png)
[🔫](https://emojipedia.org/pistol/) is not intended as a toy (water pistol / squirt gun, ray gun / phaser). 

In mid-2016, Apple deliberately adopted a glyph that resulted in semantic mayhem in cross platform communication and rendering of legacy texts. In 2017, WhatsApp in their initial release of a custom emoji set kept compatible with Apple’s design, because in their almost closed ecosystem, effectively only Apple and WhatsApp emoji glyphs can ever occur. After having been criticized for several years for having too idiosyncratic emoji designs, in early 2018, Samsung overshot the correction by also changing the pistol emoji glyph. (Few users are affected by this change yet.) Now Twitter is changing, while Microsoft, Google and Emojione are not (yet) diverging from the Unicode semantics and reference glyph. 

There was good reason for Microsoft to adopt a picture of a realistic firearm in 2016. There was no good reason for Apple to make a change in the opposite direction in a new released in the very same week. There was good reason for WhatsApp to stay compatible with Apple. There is no sufficient reason for Samsung and Twitter to follow suit.

If you want a toy gun emoji, propose one to be encoded, either on a separate code point or as a ZWJ sequence like 🔫&zwj;💦 or 🔫&zwj;💧. If you have any other reason to change the glyph, please explain it well, which Apple never did as far as I know, and be prepared to change it back.

**Comment by Jop-V** [comment] 2018-04-14 16:15
This is extremely dangerous as noted by Emojipedia.

![Emojipedia's example](https://blog.emojipedia.org/content/images/2016/08/emojipedia-pistol-emoji-cross-platform.png)

Please, do not turn Twemoji into malware.

**Comment by April93** [comment] 2018-04-15 07:36
[The vast majority of fonts](https://emojipedia.org/pistol/) match the spec. Having twitter deliberately different makes it unusable.

**Comment by bhaggs** [comment] 2018-04-24 23:39
With other major emoji vendors (Apple, Google, Samsung, Facebook) having already or are moving towards a squirt gun/water pistol for this emoji codepoint our goal is to ensure Twemoji has interoperability as it relates to ensuring the intended meaning is retained between the individual who chose the emoji and the reader who sees the emoji. This change meets that goal.

**Closed by bhaggs** 2018-04-24 23:39 UTC

**Comment by April93** [comment] 2018-04-25 02:07
If the goal is interoperability this is moving away from that goal. As every new emoji font will be using the spec. The majority of emoji fonts do not have a squirtgun, and properly follow the spec.

Why don't y'all just be honest: you're copying apple.

**Comment by Crissov** [comment] 2018-04-25 05:31
Did you know in advance about Googleʼs and Facebookʼs plans?
<https://blog.emojipedia.org/google-updates-gun-emoji/>

**Comment by April93** [comment] 2018-04-25 19:12
Sure. It's a shame that every large company is merely copy Apple and don't properly follow the spec. Perhaps of turning twemoji to be incorrect and essentially malware, how about providing both options? The correct spec, and then the mutilated emoji that doesn't properly represent what it's supposed to for the sake of compatibility with major tech companies?

**Comment by Crissov** [comment] 2018-04-25 19:16
My question was actually directed at @bhaggs. Letʼs hope the issue will be discussed and resolved in a good way next week at UTC.

**Comment by vaindil** [comment] 2018-04-27 02:09
This is reddit and it's a throwaway account (common on /r/legaladvice), but if it's true this is an actual situation with legal ramifications because of the confusion between vendors. Take it as you will.

https://www.reddit.com/r/legaladvice/comments/8f3s4p/fl_school_search_warrant/

**Comment by April93** [comment] 2018-04-27 02:15
@vaindil as you can see, having it as the incorrect squirt gun causes problems. Had his phone properly displayed it as a gun, he would've not sent that text, and the problem would have been avoided. This is exactly why font developers should follow the spec.

**Comment by DXGLdotinfo** [comment] 2018-05-20 13:55
+bhaggs
Unfortunately to make cross platform compatibility, all existing Unicode compliant devices would have to be permanently removed from service.  Unicode says for U+1F52B "Pistol" or alternatively "Handgun" or "Revolver".

Please re-open the Issue.  If you have received any threats that forced you to change the contents of the emoji, then immediately report those threats to law enforcement.

**Comment by DXGLdotinfo** [comment] 2018-05-20 14:08
Seeing the Twitter account of @bhaggs I see there is a conflict of interest here, and that he is using this to make a political statement via censorship.

**Comment by Jop-V** [comment] 2018-05-22 13:19
@DXGLdotinfo If anti-gun politics are indeed the cause of this debacle, it would not make a lot of sense as the replacement also works the other way around (when sending from a new device to an old device/compliant device). Then again, politics aren't supposed to make any sense whatsoever.

**Comment by ArmeF97** [comment] 2019-02-02 10:51
Please merge https://github.com/twitter/twemoji/pull/330

**Comment by hikari-no-yume** [comment] 2020-07-22 21:58
Hi. I know this is an old issue, and I know it might be a lost cause, but I want to revive this.

I am _not_ going to argue for just restoring the original realistic gun look however, and not because of any particular preference for the kind of gun. My concern with that is it would just exacerbate the semantic hell. Rather, I want to suggest acknowledging the semantic mess and making the emoji reflect that as unambiguously as possible. I have thought of two possible approaches:

* Make the emoji into a cross between the realistic gun and the water gun. The idea would be to try to remind the user that it is ambiguous.
* Delete the emoji, replacing it with something along the lines of the Unicode replacement character (�) or the white box frequently seen for missing characters (▯).

(I'm sure others may have better ideas than me, please don't consider these the only possibilities!)

Both may seem like drastic changes. But I think we must consider that not only is the emoji ambiguous, it is dangerously so. A message intended to contain a water pistol and received as a real gun, or vice-versa, could have serious consequences in the wrong circumstances, perhaps even life-threatening ones. If that sounds far-fetched, consider that that a single mobile phone misdisplaying Turkish I in an SMS famously [may have caused two people's deaths and three people's imprisonment](https://web.archive.org/web/20100102064618/http://www.theinquirer.net/inquirer/news/1017243/cellphone-localisation-glitch).

It may be tempting to think that the problem has been solved now that (almost?) all vendors went along with Apple's emoji change. However, consider the current Android install figures for example:

![Screenshot of “Android Platform/API Distribution” window from Android Studio, taken 2020-07-22. The most important detail it shows is Android Pie (9.0) or later being installed on only 39.5% of active devices.](https://user-images.githubusercontent.com/579774/88232008-68389500-cc75-11ea-8fcf-5e968d72c096.png)

Google only switched to the water pistol variant in Android 9, and only 39.5% of active Android devices have 9 or later. This implies that about 60% of Android devices currently in use do _not_ see the water pistol! There are probably hundreds of millions of devices out there for each variant, Android or no, and this may remain the case for years to come. So there is no clear consensus in terms of what devices in the wild do, and the potential for misunderstandings affects a very large number of users. We can't assume they all know about the fact some vendors changed the emoji glyphs, or that they actually understand what that means.

**Comment by dxgldotorg** [comment] 2020-07-22 22:08
Doesn't Google still push the censored emoji to many previous versions via its built-in apps?

With that said, last time I checked, Unicode defined it as Pistol with alternative definitions of revolver or handgun.

**Comment by hikari-no-yume** [comment] 2020-07-22 22:13
> Doesn't Google still push the censored emoji to many previous versions via its built-in apps?

I can't speak to the general experience, but my partner's old Android phone, which runs Android 8, still shows the revolver. It has fully up-to-date apps AFAIK.

> last time I checked, Unicode defined it as Pistol with alternative definitions of revolver or handgun

Only character encoding nerds (and I don't say that derisively — I am one 🙂), and possibly users of accessibility tools, know what the standard names the character. The standard did not create the semantic hell and citing the standard won't fix it.

**Comment by dxgldotorg** [comment] 2020-07-24 20:41
> Only character encoding nerds (and I don't say that derisively — I am one 🙂), and possibly users of accessibility tools, know what the standard names the character. The standard did not create the semantic hell and citing the standard won't fix it.

Microsoft classifies their Splatoon gun knockoff as pistol, perhaps due to automatically grabbing emoji names from the Unicode specification.

**Comment by dxgldotorg** [comment] 2023-03-31 19:28
Should this be re-opened due to Twitter's new ownership and political policies?
