### ISSUE TITLE
width and height missing from SVG files

### ISSUE THREAD

**Issue by autopulated** [twitter/twemoji#155] opened 2016-07-14 12:11 UTC
The missing width and height in SVG files prevents them from being resizable in older webkit browsers (specifically wkhtml2pdf/image). 

It seems like it'd be possible to generate the width and height from the viewBox property, and I don't think this breaks any other browsers.

**Comment by WebReflection** [comment] 2016-09-25 14:27
width and height were breaking pretty much everywhere which is why they are replaced in favour of viewBox:
https://github.com/twitter/twemoji/blob/gh-pages/svg.sh#L16-L25

I'm afraid nobody complained so far so it's a won't fix.
Moreover, for very old webkit I suggest using pngs instead of SVG, the performance impact is huge with SVGs on old hardware.

**Closed by WebReflection** 2016-09-25 14:27 UTC

**Comment by autopulated** [comment] 2016-09-25 15:13
OK no problem, thanks for the explanation – it's easy enough to just generate them in the build process for our use case.

**Comment by mckennapsean** [comment] 2021-11-05 19:36
For what it is worth, not specifying widths & heights causes an issue in the Firefox web browser, specifically for rendering the SVG to the canvas via `drawImage`.

I believe this is the bug on Mozilla's side: https://bugzilla.mozilla.org/show_bug.cgi?id=700533

And it's been filed as a web compatibility issue: https://webcompat.com/issues/64352

Because Firefox (today) treats a non-specified width & height as a `0x0` image, it renders as empty in canvas. Interestingly, it renders fine as a regular SVG in the browser.

Let me know if you need any examples -- it is very easy to reproduce.

I'd really hope Mozilla fixes/approves a fix for this bug on their end (and the recent priority update could be promising).
