### ISSUE TITLE
How do I turn unicode emojis to twemoji on my page.

### ISSUE THREAD

**Issue by EnderDev** [twitter/twemoji#322] opened 2018-11-24 18:24 UTC
Hi, I was wondering how I can turn https://honestly-i-hate.ender.site/i/cE5LY7.png this for example, to twemoji emojis, without getting the user to insert twemoji emojis, I just want it to convert all the unicode emojis in my div with the id "feed" into twemoji ones. 

Thanks ,Ender

**Comment by TheEssemCraft** [comment] 2018-12-04 17:55
You could try putting this code in your `head` tag:
```html
<script>
	window.onload = function() { // runs the script when the page is loading
  	  twemoji.parse(document.getElementById('feed'), { // parses the elements inside of #feed
	    folder: 'svg', // sets it to render svgs
	    ext: '.svg',
	    callback: function(iconId, options) {
        	switch (iconId) { // ignores the copyright, registered trademark, and trademark symbols
            	  case 'a9':      // © copyright
            	  case 'ae':      // ® registered trademark
            	  case '2122':    // ™ trademark
                  return false;
                }
                return ''.concat(options.base, options.size, '/', iconId, options.ext); // actually renders the emoji
	    }
	  });
	};
</script>
```

**Comment by EnderDev** [comment] 2018-12-17 20:30
Hi, I placed this in my head and a lot of errors are in console: `TypeError: node is null[Learn More] twemoji.min.js:2:7317

    grabAllTextNodes https://twemoji.maxcdn.com/2/twemoji.min.js?11.2:2 parseNode https://twemoji.maxcdn.com/2/twemoji.min.js?11.2:2 parse https://twemoji.maxcdn.com/2/twemoji.min.js?11.2:2 emojis https://bot.ender.site/profile/?id=217562587938816000:23 <anonymous> https://bot.ender.site/profile/?id=217562587938816000:16 `

**Comment by locness3** [comment] 2018-12-24 18:57
@EnderDev This seems to be aproblem with the twemoji code. Maybe put the JS on your server ?

**Comment by jdecked** [comment] 2020-05-10 04:40
This is quite old, so I'm going to close it. If you (or anyone else reading this) are still having issues, please feel free to re-open with a reproducible example.

**Closed by jdecked** 2020-05-10 04:40 UTC

**Comment by GNUGradyn** [comment] 2020-05-29 23:18
I am also getting `TypeError: node is null` 

Page: https://gralyn.app/emoji-picker/
