### ISSUE TITLE
Issue with twemoji javascript

### ISSUE THREAD

**Issue by ltblueberry0** [twitter/twemoji#260] opened 2017-11-12 18:06 UTC
I encountered an issue where an emoji is rendered as two separate emojis with the twemoji javascript. 
An example to explain: The website contains the black female surfer emoji (https://emojipedia.org/woman-surfing-type-6/) which should usually contain 5 code points. Unfortunately the last code point is missing (U+FE0F). Using the webpage without running twemoji displays the surfer correctly as one single emoji. Running twemoji on that website converts the female surfer to two different emojis: a black male surfer and a female sign. Regular webpages and some other editors do not have any problems with the missing codepoint U+FE0F (Variation Selector-16) and still display the correct emoji. 
Input to the website:       🏄🏿‍♀ (\u55356 \u57284 \u55356 \u57343 \u8205 \u9792)
Expected input:               🏄🏿‍♀️ (\u55356 \u57284 \u55356 \u57343 \u8205 \u9792 \u65039)
Unfortunately I cannot control the input into the website before the twemoji script is invoked.

How can I prevent this from happening? Or how could I adjust the twemoji script to cope with the missing codepoint U+FE0F (Variation Selector-16)?

**Comment by WebReflection** [comment] 2017-11-13 10:46
I believe the issue is that current version of the script RegExp does not support that combination so that what you see is actually the unicode fallback mechanism in action.

**Comment by ltblueberry0** [comment] 2017-11-29 18:24
the problem is that the current version of the RegExp does not capture non-fully qualified emojis.

**Comment by Nektro** [comment] 2018-01-06 03:08
This is probably not going to be fixed since Twitter is a Unicode member and only supports official sequences. See #192

**Comment by WebReflection** [comment] 2018-06-08 14:13
Closing as there's no actionable task in here as per #192.

**Closed by WebReflection** 2018-06-08 14:13 UTC
