### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by dheerajjaiswal08** [twitter/twemoji#269] opened 2017-12-18 07:47 UTC
Hello sir/ma'am,

When I want to parse the unicode directly it works 
means,
twemoji.parse("\ud83d\ude0d\ud83d\ude0a\ud83d\ude04\ud83d\ude14");

but when i get the value form my data base and then pass it to the function it not works
var test = getValuefromdb();
twemoji.parse(test);

Sir/ma'am Please Help
Thank you

**Comment by WebReflection** [comment] 2017-12-18 16:08
that means your database does not return the same unicode string.

Without a dump of that `test` variable there's not much we can do to help.

**Comment by Mindbowser** [comment] 2018-01-22 12:08
Same issue, any luck? When we print values coming from backend it seems they are correct, any idea?

**Comment by Mindbowser** [comment] 2018-01-22 12:15
seems like duplicate of https://github.com/twitter/twemoji/issues/206

**Comment by WebReflection** [comment] 2018-06-08 14:12
> seems like duplicate of #206 

also no answers in ages so I am closing this as there's nothing to do here.

**Closed by WebReflection** 2018-06-08 14:12 UTC
