### ISSUE TITLE
Implied variant selector for zwj sequence emojis?

### ISSUE THREAD

**Issue by sp00x** [twitter/twemoji#351] opened 2019-04-25 10:15 UTC
The sequence "running woman" is (running person) + (ZWJ) + (female symbol), or 1f3c3 200d 2640 (\ud83c\udfc3\u200d\u2640)

It seems twemoji renders this as (image of running man) (female symbol), where as Chrome and others imply this to be displayed as the simgle (running woman) emoji.

Twemoji requires an additional variant selector-16 (\ufe0f) at the end for it to display as a single glyph, i.e. 1f3c3 200d 2640 fe0f

Is this intended, or a bug? Or can you override the default behavior somewhere?

**Comment by polarathene** [comment] 2019-10-07 10:44
> It seems twemoji renders this as (image of running man) (female symbol), where as Chrome and others imply this to be displayed as the simgle (running woman) emoji.

Firefox bundles it's own version of twemoji afaik, so your issue might be with their fork? Perhaps provide a reproduction case and screenshot.

It seems to render correctly for me on [emojipedia](https://emojipedia.org/woman-running/) with the CSS font-family updated to be "Twemoji Mozilla". Also verified on getemoji.com as the Twitter version shown on emojipedia link.

If I put the sequence you're experiencing into an HTML element `&#x1f3c3&#x200d&#x2640`, it will display as you describe (🏃‍) + (♀)(fun fact, at least in Chrome selecting the two from firefox and copy/pasting into Chrome text input here merged the two automatically into the running girl. Can't seem to replicate that in Firefox).

`&#x1f3c3&#x200d&#x2640&#xFE0F` will of course provide the result you're requesting. The emojipedia link defines the codepoint for "Running Woman" as requiring that VS16 codepoint. So I would not say this is a bug.

Behaviour regarding Variation Selectors seems to vary by browser and platform. See [here](https://github.com/googlefonts/noto-emoji/issues/266) for an example of such.

**Comment by jdecked** [comment] 2020-10-13 21:58
Previously, Twemoji intended to only provide full support for fully qualified emojis (which, without the VS16 at the end, the "running woman" sequence is not). This is changing as part of the solution to #405, since we recognize that input methods vary by vendor on whether or not they stick strictly to only inputting fully qualified emojis. Our plan for the future is to be a bit less strict, so that that sequence for "running woman" without the VS16 at the end is accepted.

**Closed by jdecked** 2020-10-13 21:58 UTC
Labels: duplicate
