### ISSUE TITLE
Introduction of the emoji of the Belarusian flag of 1994

### ISSUE THREAD

**Issue by beldelo** [twitter/twemoji#525] opened 2022-01-28 17:43 UTC
I would like to ask you to add an official emoji with the WRW flag (see the attached photo) as a sign of support and solidarity with the peaceful protesters of Belarus, it will be a nice support from your side^^

![1EoQgRIhW7KnSPlofdimCQ](https://user-images.githubusercontent.com/29740248/151595822-edf64b97-dbe9-446f-8089-3127c6a06b54.png)

**Comment by jdecked** [comment] 2022-01-28 21:23
Duplicate of #444

**Closed by jdecked** 2022-01-28 21:23 UTC
