### ISSUE TITLE
preview-svg.html doesn't load emoji

### ISSUE THREAD

**Issue by h3oCharles** [twitter/twemoji#479] opened 2021-03-10 21:14 UTC
**Describe the bug**
downloading the source code for release 13.0.1 and opening src/test/preview-svg.html does give a page with emotes, however they do not turn into twitter emoji.

**Expected behavior**
page with vector twitter emojis

**Screenshots**
the failed preview page
https://i.imgur.com/jY47qR9.png

opening chrome's dev tools console shows an error 404 and line 3112 in the html being errorus
https://i.imgur.com/4Fne7Qf.png

line 3112 being:
`twemoji.parse(ul, {"folder":"../svg","ext":".svg","base":""});`

**Environment**
Windows 10 Version 10.0.19042 Build 19042
Google Chrome Version 88.0.4324.190 (Official Build) (64-bit)

**Comment by jdecked** [comment] 2021-03-11 05:17
Please do not delete sections from the issue template. The "steps to reproduce" section is there for a very important reason: without you providing reproduction steps, I will sincerely respond, "It works on my computer" then close the issue when I can't manage to reproduce your issue. This is important even when the reproduction steps seem obvious to you, because they may not be obvious to maintainers, who typically interact with the code in a different way than the average user. [Here](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) is a great resource on how to file helpful bug reports.

That aside, luckily I do have a good guess on what you're doing — thanks for reporting, fixed in 54b69b0d730f8a2c3ffc9cccd26e4b69c253a2a6.

**Closed by jdecked** 2021-03-11 05:17 UTC

**Comment by h3oCharles** [comment] 2021-03-20 13:46
1. download release 13.0.1
2. extract it
3. open src folder
4. open test folder
5. 5. open preview-svg.html using chrome
