### ISSUE TITLE
Apple rejection

### ISSUE THREAD

**Issue by raulriera** [twitter/twemoji#229] opened 2017-05-26 01:42 UTC
Hi everyone, 

Probably not the correct place for this, but I'm been getting a back and forward with Apple about this, has anyone been able to sort this out with them? They refuse to read the licenses in this repo apparently 

> Design 4.4.3
> 
> While we understand the information you have provided, your app must comply with the App Store Review Guidelines to be appropriate for the App Store. 
> 
> Your app includes images of third party emoji used as stickers without authorization from the necessary third party. 
> 
> To resolve this issue, please revise the images used in your sticker pack. Otherwise, please provide documentation from Twitter demonstrating your rights to use the emoji imagery as stickers in your app. 
> 

Thanks!

**Comment by Crissov** [comment] 2017-05-26 10:33
Just to clarify: you are trying to get a sticker pack into Apple's (iMessage) app store that uses Twemoji graphics verbatim.

Maybe it would help if Twemoji assets lived in their own repository and had a `LICENSE` file instead of `LICENSE-GRAPHICS`, because Github shows a simple synopsis for the former but not the latter. Perhaps an additional pointer to https://creativecommons.org/licenses/by/4.0/ would do the trick, though.

**Comment by WebReflection** [comment] 2017-05-26 12:03
FYI This repository is mirrored by MaxCDN. This is how it's been set up since the beginning and assets cannot possibly be moved anywhere else or people using twemoji via MaxCDN will break.

Assets are also used to generate the JS file so any other solution different from moving assets from here would be probably better.

**Comment by raulriera** [comment] 2017-05-26 12:29
> Just to clarify: you are trying to get a sticker pack into Apple's (iMessage) app store that uses Twemoji graphics verbatim.

Yes, it allows you to compose new emojis by overlapping them, resize, rotate, etc. But yes, it includes all the twitter emojis

**Comment by Crissov** [comment] 2017-05-26 12:37
@WebReflection Submodules would not work for Maxcdn?

**Comment by WebReflection** [comment] 2017-05-26 12:53
@Crissov I don't know. If they just pull from here without recursion for submodules too it'd be a problem but I am not responsible for that setup.

**Comment by siburb** [comment] 2017-11-16 02:22
@raulriera I'm anticipating having a similar issue. Did you get this resolved with Apple?

**Comment by raulriera** [comment] 2017-11-16 02:38
I made a completely new icon

**Comment by WebReflection** [comment] 2017-11-16 16:04
so ... the issue is that you were using a twitter emoji as App icon?

Can you please elaborate a bit more what was the issue, how you actually solved it, and if it had nothing to do with this ticket, maybe close it too?

Thanks!

**Comment by raulriera** [comment] 2017-11-16 16:11
> so ... the issue is that you were using a twitter emoji as App icon?

Yes, this image shows the old vs new... the old one was rejected because it was just the emoji without changes

![screen shot 2017-11-16 at 11 09 10 am](https://user-images.githubusercontent.com/24159/32901794-ae9548a6-cabe-11e7-9e23-1ba764e5a8db.png)

The disclaimer where I actually show the emojis was me, they didn't ask about that... but I felt it needed more acknowledgement that just the website (space is sooo crammed in iMessage apps)

**Comment by WebReflection** [comment] 2017-11-16 20:05
thanks for elaborating.

**Closed by WebReflection** 2017-11-16 20:05 UTC
