### ISSUE TITLE
v12.1.1 broken on npm

### ISSUE THREAD

**Issue by keithlayne** [twitter/twemoji#365] opened 2019-07-02 07:34 UTC
I just updated from 12.0.1 to 12.1.1 from npm and that version of the package is broken.

Specifically, it does not include the dist directory.  From the recent commits it looks like the build/publish scripts were tweaked, which I'm guessing is the culprit.

Unfortunately I don't have time right now to debug, but hopefully it's a relatively quick and easy fix.

**Comment by yhatt** [comment] 2019-07-02 14:42
I have received the report caused by this matter in my tool :cry:
https://github.com/marp-team/marp-cli/issues/121

**Comment by VictorQueiroz** [comment] 2019-07-02 17:01
I can confirm it. That's all I have in the installed folder:
```
$ tree node_modules/twemoji
node_modules/twemoji
├── LICENSE
├── LICENSE-GRAPHICS
├── node_modules
│   ├── fs-extra
│   │   ├── CHANGELOG.md
│   │   ├── lib
│   │   │   ├── copy
│   │   │   │   ├── copy.js
│   │   │   │   └── index.js
│   │   │   ├── copy-sync
│   │   │   │   ├── copy-sync.js
│   │   │   │   └── index.js
│   │   │   ├── empty
│   │   │   │   └── index.js
│   │   │   ├── ensure
│   │   │   │   ├── file.js
│   │   │   │   ├── index.js
│   │   │   │   ├── link.js
│   │   │   │   ├── symlink.js
│   │   │   │   ├── symlink-paths.js
│   │   │   │   └── symlink-type.js
│   │   │   ├── fs
│   │   │   │   └── index.js
│   │   │   ├── index.js
│   │   │   ├── json
│   │   │   │   ├── index.js
│   │   │   │   ├── jsonfile.js
│   │   │   │   ├── output-json.js
│   │   │   │   └── output-json-sync.js
│   │   │   ├── mkdirs
│   │   │   │   ├── index.js
│   │   │   │   ├── mkdirs.js
│   │   │   │   ├── mkdirs-sync.js
│   │   │   │   └── win32.js
│   │   │   ├── move
│   │   │   │   ├── index.js
│   │   │   │   └── move.js
│   │   │   ├── move-sync
│   │   │   │   ├── index.js
│   │   │   │   └── move-sync.js
│   │   │   ├── output
│   │   │   │   └── index.js
│   │   │   ├── path-exists
│   │   │   │   └── index.js
│   │   │   ├── remove
│   │   │   │   ├── index.js
│   │   │   │   └── rimraf.js
│   │   │   └── util
│   │   │       ├── buffer.js
│   │   │       ├── stat.js
│   │   │       └── utimes.js
│   │   ├── LICENSE
│   │   ├── node_modules
│   │   │   └── jsonfile
│   │   │       ├── CHANGELOG.md
│   │   │       ├── index.js
│   │   │       ├── LICENSE
│   │   │       ├── package.json
│   │   │       └── README.md
│   │   ├── package.json
│   │   └── README.md
│   └── jsonfile
│       ├── CHANGELOG.md
│       ├── index.js
│       ├── LICENSE
│       ├── package.json
│       └── README.md
├── package.json
└── README.md

19 directories, 50 files
```

**Comment by n8downs** [comment] 2019-07-02 17:36
Thanks for catching this, and apologies I didn't catch it myself! 

@keithlayne was correct: 
> From the recent commits it looks like the build/publish scripts were tweaked, which I'm guessing is the culprit.

Should be addressed in https://github.com/twitter/twemoji/releases/tag/v12.1.2

**Closed by n8downs** 2019-07-02 17:36 UTC
